// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
)

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccountByCodeHash = `-- name: GetAccountByCodeHash :one
SELECT id, code_hash, status, created_at, updated_at FROM accounts WHERE code_hash = ?
`

func (q *Queries) GetAccountByCodeHash(ctx context.Context, codeHash []byte) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByCodeHash, codeHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, code_hash, status, created_at, updated_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, code_hash, status, created_at, updated_at)
VALUES (?, ?, 'active', ?, ?)
`

type InsertAccountParams struct {
	ID        string `json:"id"`
	CodeHash  []byte `json:"code_hash"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.CodeHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
