// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getCycleByID = `-- name: GetCycleByID :one
SELECT id, account_id, start_date, end_date, length_days, bleeding_days, certainty, source, notes, client_rev, created_at, updated_at, deleted_at FROM cycles WHERE id = ? AND account_id = ?
`

type GetCycleByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetCycleByID(ctx context.Context, arg GetCycleByIDParams) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleByID, arg.ID, arg.AccountID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StartDate,
		&i.EndDate,
		&i.LengthDays,
		&i.BleedingDays,
		&i.Certainty,
		&i.Source,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestCycleStart = `-- name: GetLatestCycleStart :one
SELECT start_date FROM cycles
WHERE account_id = ? AND deleted_at IS NULL
ORDER BY start_date DESC
LIMIT 1
`

func (q *Queries) GetLatestCycleStart(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestCycleStart, accountID)
	var start_date string
	err := row.Scan(&start_date)
	return start_date, err
}

const listCycleStarts = `-- name: ListCycleStarts :many
SELECT start_date FROM cycles
WHERE account_id = ? AND deleted_at IS NULL
ORDER BY start_date
`

func (q *Queries) ListCycleStarts(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCycleStarts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var start_date string
		if err := rows.Scan(&start_date); err != nil {
			return nil, err
		}
		items = append(items, start_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByRange = `-- name: ListCyclesByRange :many
SELECT id, account_id, start_date, end_date, length_days, bleeding_days, certainty, source, notes, client_rev, created_at, updated_at, deleted_at FROM cycles
WHERE account_id = ? AND deleted_at IS NULL
  AND start_date >= ? AND start_date <= ?
ORDER BY start_date DESC
`

type ListCyclesByRangeParams struct {
	AccountID   string `json:"account_id"`
	StartDate   string `json:"start_date"`
	StartDate_2 string `json:"start_date_2"`
}

func (q *Queries) ListCyclesByRange(ctx context.Context, arg ListCyclesByRangeParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByRange, arg.AccountID, arg.StartDate, arg.StartDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StartDate,
			&i.EndDate,
			&i.LengthDays,
			&i.BleedingDays,
			&i.Certainty,
			&i.Source,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCycle = `-- name: UpsertCycle :execrows

INSERT INTO cycles (
    id, account_id, start_date, end_date, length_days, bleeding_days,
    certainty, source, notes, client_rev, created_at, updated_at, deleted_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    start_date    = excluded.start_date,
    end_date      = excluded.end_date,
    length_days   = excluded.length_days,
    bleeding_days = excluded.bleeding_days,
    certainty     = excluded.certainty,
    source        = excluded.source,
    notes         = excluded.notes,
    client_rev    = excluded.client_rev,
    created_at    = excluded.created_at,
    updated_at    = excluded.updated_at,
    deleted_at    = excluded.deleted_at
WHERE excluded.updated_at > cycles.updated_at
   OR (excluded.updated_at = cycles.updated_at AND excluded.client_rev > cycles.client_rev)
`

type UpsertCycleParams struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	StartDate    string         `json:"start_date"`
	EndDate      sql.NullString `json:"end_date"`
	LengthDays   sql.NullInt64  `json:"length_days"`
	BleedingDays sql.NullInt64  `json:"bleeding_days"`
	Certainty    string         `json:"certainty"`
	Source       string         `json:"source"`
	Notes        string         `json:"notes"`
	ClientRev    string         `json:"client_rev"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	DeletedAt    sql.NullString `json:"deleted_at"`
}

// Entity-level last-write-wins: the update applies only when the incoming
// record is newer (updated_at, then client_rev). Affected rows = 0 means the
// pushed record lost; the handler returns the server state as a conflict.
func (q *Queries) UpsertCycle(ctx context.Context, arg UpsertCycleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertCycle,
		arg.ID,
		arg.AccountID,
		arg.StartDate,
		arg.EndDate,
		arg.LengthDays,
		arg.BleedingDays,
		arg.Certainty,
		arg.Source,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
