// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT devices.id, devices.account_id, devices.name, devices.token_hash, devices.created_at, devices.last_seen_at, devices.revoked_at, accounts.status AS account_status
FROM devices
JOIN accounts ON accounts.id = devices.account_id
WHERE devices.token_hash = ?
`

type GetDeviceByTokenHashRow struct {
	ID            string         `json:"id"`
	AccountID     string         `json:"account_id"`
	Name          string         `json:"name"`
	TokenHash     []byte         `json:"token_hash"`
	CreatedAt     string         `json:"created_at"`
	LastSeenAt    sql.NullString `json:"last_seen_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
	AccountStatus string         `json:"account_status"`
}

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash []byte) (GetDeviceByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i GetDeviceByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.AccountStatus,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, account_id, name, token_hash, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertDeviceParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Name      string `json:"name"`
	TokenHash []byte `json:"token_hash"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const listDevicesByAccount = `-- name: ListDevicesByAccount :many
SELECT id, account_id, name, token_hash, created_at, last_seen_at, revoked_at FROM devices
WHERE account_id = ?
ORDER BY created_at
`

func (q *Queries) ListDevicesByAccount(ctx context.Context, accountID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE devices SET revoked_at = ? WHERE id = ? AND account_id = ?
`

type RevokeDeviceParams struct {
	RevokedAt sql.NullString `json:"revoked_at"`
	ID        string         `json:"id"`
	AccountID string         `json:"account_id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeDevice, arg.RevokedAt, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = ? WHERE id = ?
`

type TouchDeviceParams struct {
	LastSeenAt sql.NullString `json:"last_seen_at"`
	ID         string         `json:"id"`
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchDevice, arg.LastSeenAt, arg.ID)
	return err
}
