// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duo.sql

package dbgen

import (
	"context"
	"database/sql"
)

const acceptDuoLink = `-- name: AcceptDuoLink :exec
UPDATE duo_links
SET partner_account_id = ?, status = 'active', code_hash = NULL, updated_at = ?
WHERE id = ? AND status = 'pending'
`

type AcceptDuoLinkParams struct {
	PartnerAccountID sql.NullString `json:"partner_account_id"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) AcceptDuoLink(ctx context.Context, arg AcceptDuoLinkParams) error {
	_, err := q.db.ExecContext(ctx, acceptDuoLink, arg.PartnerAccountID, arg.UpdatedAt, arg.ID)
	return err
}

const ackSupportRequest = `-- name: AckSupportRequest :exec
UPDATE support_requests SET acknowledged_at = ? WHERE id = ?
`

type AckSupportRequestParams struct {
	AcknowledgedAt sql.NullString `json:"acknowledged_at"`
	ID             string         `json:"id"`
}

func (q *Queries) AckSupportRequest(ctx context.Context, arg AckSupportRequestParams) error {
	_, err := q.db.ExecContext(ctx, ackSupportRequest, arg.AcknowledgedAt, arg.ID)
	return err
}

const getActiveDuoLinkByOwner = `-- name: GetActiveDuoLinkByOwner :one
SELECT id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at, revoked_at FROM duo_links
WHERE owner_account_id = ? AND status = 'active'
`

func (q *Queries) GetActiveDuoLinkByOwner(ctx context.Context, ownerAccountID string) (DuoLink, error) {
	row := q.db.QueryRowContext(ctx, getActiveDuoLinkByOwner, ownerAccountID)
	var i DuoLink
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.PartnerAccountID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveDuoLinkByPartner = `-- name: GetActiveDuoLinkByPartner :one
SELECT id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at, revoked_at FROM duo_links
WHERE partner_account_id = ? AND status = 'active'
`

func (q *Queries) GetActiveDuoLinkByPartner(ctx context.Context, partnerAccountID sql.NullString) (DuoLink, error) {
	row := q.db.QueryRowContext(ctx, getActiveDuoLinkByPartner, partnerAccountID)
	var i DuoLink
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.PartnerAccountID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDuoLinkByID = `-- name: GetDuoLinkByID :one
SELECT id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at, revoked_at FROM duo_links WHERE id = ?
`

func (q *Queries) GetDuoLinkByID(ctx context.Context, id string) (DuoLink, error) {
	row := q.db.QueryRowContext(ctx, getDuoLinkByID, id)
	var i DuoLink
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.PartnerAccountID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPendingDuoLinkByCodeHash = `-- name: GetPendingDuoLinkByCodeHash :one
SELECT id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at, revoked_at FROM duo_links
WHERE code_hash = ? AND status = 'pending'
`

func (q *Queries) GetPendingDuoLinkByCodeHash(ctx context.Context, codeHash []byte) (DuoLink, error) {
	row := q.db.QueryRowContext(ctx, getPendingDuoLinkByCodeHash, codeHash)
	var i DuoLink
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.PartnerAccountID,
		&i.CodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSupportRequestByID = `-- name: GetSupportRequestByID :one
SELECT id, link_id, author_role, kind, message, created_at, acknowledged_at FROM support_requests WHERE id = ?
`

func (q *Queries) GetSupportRequestByID(ctx context.Context, id string) (SupportRequest, error) {
	row := q.db.QueryRowContext(ctx, getSupportRequestByID, id)
	var i SupportRequest
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.AuthorRole,
		&i.Kind,
		&i.Message,
		&i.CreatedAt,
		&i.AcknowledgedAt,
	)
	return i, err
}

const insertDuoLink = `-- name: InsertDuoLink :exec

INSERT INTO duo_links (
    id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at
) VALUES (?, ?, ?, ?, 'pending', ?, ?)
`

type InsertDuoLinkParams struct {
	ID               string         `json:"id"`
	OwnerAccountID   string         `json:"owner_account_id"`
	PartnerAccountID sql.NullString `json:"partner_account_id"`
	CodeHash         []byte         `json:"code_hash"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

// Duo queries. Designed in docs/api.md; handlers land after the core sync
// path is proven.
func (q *Queries) InsertDuoLink(ctx context.Context, arg InsertDuoLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertDuoLink,
		arg.ID,
		arg.OwnerAccountID,
		arg.PartnerAccountID,
		arg.CodeHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSupportRequest = `-- name: InsertSupportRequest :exec
INSERT INTO support_requests (id, link_id, author_role, kind, message, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSupportRequestParams struct {
	ID         string `json:"id"`
	LinkID     string `json:"link_id"`
	AuthorRole string `json:"author_role"`
	Kind       string `json:"kind"`
	Message    string `json:"message"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertSupportRequest(ctx context.Context, arg InsertSupportRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertSupportRequest,
		arg.ID,
		arg.LinkID,
		arg.AuthorRole,
		arg.Kind,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const listActiveGrantsByLink = `-- name: ListActiveGrantsByLink :many
SELECT id, link_id, field, granted_at, revoked_at FROM duo_grants
WHERE link_id = ? AND revoked_at IS NULL
`

func (q *Queries) ListActiveGrantsByLink(ctx context.Context, linkID string) ([]DuoGrant, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGrantsByLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuoGrant{}
	for rows.Next() {
		var i DuoGrant
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Field,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuoLinksForAccount = `-- name: ListDuoLinksForAccount :many
SELECT id, owner_account_id, partner_account_id, code_hash, status, created_at, updated_at, revoked_at FROM duo_links
WHERE owner_account_id = ? OR partner_account_id = ?
ORDER BY created_at DESC
`

type ListDuoLinksForAccountParams struct {
	OwnerAccountID   string         `json:"owner_account_id"`
	PartnerAccountID sql.NullString `json:"partner_account_id"`
}

func (q *Queries) ListDuoLinksForAccount(ctx context.Context, arg ListDuoLinksForAccountParams) ([]DuoLink, error) {
	rows, err := q.db.QueryContext(ctx, listDuoLinksForAccount, arg.OwnerAccountID, arg.PartnerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuoLink{}
	for rows.Next() {
		var i DuoLink
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.PartnerAccountID,
			&i.CodeHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportRequestsByLink = `-- name: ListSupportRequestsByLink :many
SELECT id, link_id, author_role, kind, message, created_at, acknowledged_at FROM support_requests
WHERE link_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListSupportRequestsByLinkParams struct {
	LinkID string `json:"link_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListSupportRequestsByLink(ctx context.Context, arg ListSupportRequestsByLinkParams) ([]SupportRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSupportRequestsByLink, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportRequest{}
	for rows.Next() {
		var i SupportRequest
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.AuthorRole,
			&i.Kind,
			&i.Message,
			&i.CreatedAt,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDuoLink = `-- name: RevokeDuoLink :execrows
UPDATE duo_links
SET status = 'revoked', revoked_at = ?, updated_at = ?
WHERE id = ? AND status IN ('active', 'pending')
`

type RevokeDuoLinkParams struct {
	RevokedAt sql.NullString `json:"revoked_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) RevokeDuoLink(ctx context.Context, arg RevokeDuoLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeDuoLink, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeGrant = `-- name: RevokeGrant :exec
UPDATE duo_grants SET revoked_at = ? WHERE link_id = ? AND field = ?
`

type RevokeGrantParams struct {
	RevokedAt sql.NullString `json:"revoked_at"`
	LinkID    string         `json:"link_id"`
	Field     string         `json:"field"`
}

func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) error {
	_, err := q.db.ExecContext(ctx, revokeGrant, arg.RevokedAt, arg.LinkID, arg.Field)
	return err
}

const upsertGrant = `-- name: UpsertGrant :exec
INSERT INTO duo_grants (id, link_id, field, granted_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(link_id, field) DO UPDATE SET
    granted_at = excluded.granted_at,
    revoked_at = NULL
`

type UpsertGrantParams struct {
	ID        string `json:"id"`
	LinkID    string `json:"link_id"`
	Field     string `json:"field"`
	GrantedAt string `json:"granted_at"`
}

func (q *Queries) UpsertGrant(ctx context.Context, arg UpsertGrantParams) error {
	_, err := q.db.ExecContext(ctx, upsertGrant,
		arg.ID,
		arg.LinkID,
		arg.Field,
		arg.GrantedAt,
	)
	return err
}
