// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Account struct {
	ID        string `json:"id"`
	CodeHash  []byte `json:"code_hash"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AccountSetting struct {
	AccountID          string `json:"account_id"`
	SettingsCiphertext []byte `json:"settings_ciphertext"`
	UpdatedAt          string `json:"updated_at"`
}

type Device struct {
	ID         string         `json:"id"`
	AccountID  string         `json:"account_id"`
	Name       string         `json:"name"`
	TokenHash  []byte         `json:"token_hash"`
	CreatedAt  string         `json:"created_at"`
	LastSeenAt sql.NullString `json:"last_seen_at"`
	RevokedAt  sql.NullString `json:"revoked_at"`
}

type DuoGrant struct {
	ID        string         `json:"id"`
	LinkID    string         `json:"link_id"`
	Field     string         `json:"field"`
	GrantedAt string         `json:"granted_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

type DuoLink struct {
	ID               string         `json:"id"`
	OwnerAccountID   string         `json:"owner_account_id"`
	PartnerAccountID sql.NullString `json:"partner_account_id"`
	CodeHash         []byte         `json:"code_hash"`
	Status           string         `json:"status"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	RevokedAt        sql.NullString `json:"revoked_at"`
}

type DuoPayload struct {
	LinkID     string `json:"link_id"`
	Ciphertext []byte `json:"ciphertext"`
	UpdatedAt  string `json:"updated_at"`
}

type Record struct {
	AccountID  string `json:"account_id"`
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	ClientRev  string `json:"client_rev"`
	Ciphertext []byte `json:"ciphertext"`
	Deleted    int64  `json:"deleted"`
	UpdatedAt  string `json:"updated_at"`
	RecordedAt string `json:"recorded_at"`
}

type SupportRequest struct {
	ID                string         `json:"id"`
	LinkID            string         `json:"link_id"`
	AuthorRole        string         `json:"author_role"`
	Kind              string         `json:"kind"`
	MessageCiphertext []byte         `json:"message_ciphertext"`
	CreatedAt         string         `json:"created_at"`
	AcknowledgedAt    sql.NullString `json:"acknowledged_at"`
}

type SyncChange struct {
	Seq        int64  `json:"seq"`
	AccountID  string `json:"account_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	ClientRev  string `json:"client_rev"`
	Deleted    int64  `json:"deleted"`
	Ciphertext []byte `json:"ciphertext"`
	UpdatedAt  string `json:"updated_at"`
	RecordedAt string `json:"recorded_at"`
}
