// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getBiomarkerObservationByID = `-- name: GetBiomarkerObservationByID :one
SELECT id, account_id, observed_date, bbt_celsius, bbt_time, bbt_quality, cervical_fluid, cervix_position, cervix_firmness, notes, client_rev, created_at, updated_at, deleted_at FROM biomarker_observations WHERE id = ? AND account_id = ?
`

type GetBiomarkerObservationByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetBiomarkerObservationByID(ctx context.Context, arg GetBiomarkerObservationByIDParams) (BiomarkerObservation, error) {
	row := q.db.QueryRowContext(ctx, getBiomarkerObservationByID, arg.ID, arg.AccountID)
	var i BiomarkerObservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ObservedDate,
		&i.BbtCelsius,
		&i.BbtTime,
		&i.BbtQuality,
		&i.CervicalFluid,
		&i.CervixPosition,
		&i.CervixFirmness,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBleedingObservationByID = `-- name: GetBleedingObservationByID :one
SELECT id, account_id, observed_date, flow, intermenstrual, product_count, notes, client_rev, created_at, updated_at, deleted_at FROM bleeding_observations WHERE id = ? AND account_id = ?
`

type GetBleedingObservationByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetBleedingObservationByID(ctx context.Context, arg GetBleedingObservationByIDParams) (BleedingObservation, error) {
	row := q.db.QueryRowContext(ctx, getBleedingObservationByID, arg.ID, arg.AccountID)
	var i BleedingObservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ObservedDate,
		&i.Flow,
		&i.Intermenstrual,
		&i.ProductCount,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDailyEntryByID = `-- name: GetDailyEntryByID :one
SELECT id, account_id, entry_date, pain_level, mood_level, energy_level, notes, client_rev, created_at, updated_at, deleted_at FROM daily_entries WHERE id = ? AND account_id = ?
`

type GetDailyEntryByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetDailyEntryByID(ctx context.Context, arg GetDailyEntryByIDParams) (DailyEntry, error) {
	row := q.db.QueryRowContext(ctx, getDailyEntryByID, arg.ID, arg.AccountID)
	var i DailyEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EntryDate,
		&i.PainLevel,
		&i.MoodLevel,
		&i.EnergyLevel,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMedicationLogByID = `-- name: GetMedicationLogByID :one
SELECT id, account_id, log_date, taken_at, name, dose, kind, notes, client_rev, created_at, updated_at, deleted_at FROM medication_logs WHERE id = ? AND account_id = ?
`

type GetMedicationLogByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetMedicationLogByID(ctx context.Context, arg GetMedicationLogByIDParams) (MedicationLog, error) {
	row := q.db.QueryRowContext(ctx, getMedicationLogByID, arg.ID, arg.AccountID)
	var i MedicationLog
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LogDate,
		&i.TakenAt,
		&i.Name,
		&i.Dose,
		&i.Kind,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSymptomDefinitionByID = `-- name: GetSymptomDefinitionByID :one
SELECT id, account_id, "key", label, category, builtin, active, client_rev, created_at, updated_at, deleted_at FROM symptom_definitions WHERE id = ? AND account_id = ?
`

type GetSymptomDefinitionByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetSymptomDefinitionByID(ctx context.Context, arg GetSymptomDefinitionByIDParams) (SymptomDefinition, error) {
	row := q.db.QueryRowContext(ctx, getSymptomDefinitionByID, arg.ID, arg.AccountID)
	var i SymptomDefinition
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Key,
		&i.Label,
		&i.Category,
		&i.Builtin,
		&i.Active,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSymptomLogByID = `-- name: GetSymptomLogByID :one
SELECT id, account_id, log_date, logged_at, symptom_key, severity, notes, client_rev, created_at, updated_at, deleted_at FROM symptom_logs WHERE id = ? AND account_id = ?
`

type GetSymptomLogByIDParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetSymptomLogByID(ctx context.Context, arg GetSymptomLogByIDParams) (SymptomLog, error) {
	row := q.db.QueryRowContext(ctx, getSymptomLogByID, arg.ID, arg.AccountID)
	var i SymptomLog
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LogDate,
		&i.LoggedAt,
		&i.SymptomKey,
		&i.Severity,
		&i.Notes,
		&i.ClientRev,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBiomarkerObservationsByRange = `-- name: ListBiomarkerObservationsByRange :many
SELECT id, account_id, observed_date, bbt_celsius, bbt_time, bbt_quality, cervical_fluid, cervix_position, cervix_firmness, notes, client_rev, created_at, updated_at, deleted_at FROM biomarker_observations
WHERE account_id = ? AND deleted_at IS NULL
  AND observed_date >= ? AND observed_date <= ?
ORDER BY observed_date
`

type ListBiomarkerObservationsByRangeParams struct {
	AccountID      string `json:"account_id"`
	ObservedDate   string `json:"observed_date"`
	ObservedDate_2 string `json:"observed_date_2"`
}

func (q *Queries) ListBiomarkerObservationsByRange(ctx context.Context, arg ListBiomarkerObservationsByRangeParams) ([]BiomarkerObservation, error) {
	rows, err := q.db.QueryContext(ctx, listBiomarkerObservationsByRange, arg.AccountID, arg.ObservedDate, arg.ObservedDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BiomarkerObservation{}
	for rows.Next() {
		var i BiomarkerObservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ObservedDate,
			&i.BbtCelsius,
			&i.BbtTime,
			&i.BbtQuality,
			&i.CervicalFluid,
			&i.CervixPosition,
			&i.CervixFirmness,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBleedingObservationsByRange = `-- name: ListBleedingObservationsByRange :many
SELECT id, account_id, observed_date, flow, intermenstrual, product_count, notes, client_rev, created_at, updated_at, deleted_at FROM bleeding_observations
WHERE account_id = ? AND deleted_at IS NULL
  AND observed_date >= ? AND observed_date <= ?
ORDER BY observed_date
`

type ListBleedingObservationsByRangeParams struct {
	AccountID      string `json:"account_id"`
	ObservedDate   string `json:"observed_date"`
	ObservedDate_2 string `json:"observed_date_2"`
}

func (q *Queries) ListBleedingObservationsByRange(ctx context.Context, arg ListBleedingObservationsByRangeParams) ([]BleedingObservation, error) {
	rows, err := q.db.QueryContext(ctx, listBleedingObservationsByRange, arg.AccountID, arg.ObservedDate, arg.ObservedDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BleedingObservation{}
	for rows.Next() {
		var i BleedingObservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ObservedDate,
			&i.Flow,
			&i.Intermenstrual,
			&i.ProductCount,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyEntriesByRange = `-- name: ListDailyEntriesByRange :many
SELECT id, account_id, entry_date, pain_level, mood_level, energy_level, notes, client_rev, created_at, updated_at, deleted_at FROM daily_entries
WHERE account_id = ? AND deleted_at IS NULL
  AND entry_date >= ? AND entry_date <= ?
ORDER BY entry_date
`

type ListDailyEntriesByRangeParams struct {
	AccountID   string `json:"account_id"`
	EntryDate   string `json:"entry_date"`
	EntryDate_2 string `json:"entry_date_2"`
}

func (q *Queries) ListDailyEntriesByRange(ctx context.Context, arg ListDailyEntriesByRangeParams) ([]DailyEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDailyEntriesByRange, arg.AccountID, arg.EntryDate, arg.EntryDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyEntry{}
	for rows.Next() {
		var i DailyEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EntryDate,
			&i.PainLevel,
			&i.MoodLevel,
			&i.EnergyLevel,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationLogsByRange = `-- name: ListMedicationLogsByRange :many
SELECT id, account_id, log_date, taken_at, name, dose, kind, notes, client_rev, created_at, updated_at, deleted_at FROM medication_logs
WHERE account_id = ? AND deleted_at IS NULL
  AND log_date >= ? AND log_date <= ?
ORDER BY log_date, taken_at
`

type ListMedicationLogsByRangeParams struct {
	AccountID string `json:"account_id"`
	LogDate   string `json:"log_date"`
	LogDate_2 string `json:"log_date_2"`
}

func (q *Queries) ListMedicationLogsByRange(ctx context.Context, arg ListMedicationLogsByRangeParams) ([]MedicationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMedicationLogsByRange, arg.AccountID, arg.LogDate, arg.LogDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationLog{}
	for rows.Next() {
		var i MedicationLog
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LogDate,
			&i.TakenAt,
			&i.Name,
			&i.Dose,
			&i.Kind,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymptomDefinitions = `-- name: ListSymptomDefinitions :many
SELECT id, account_id, "key", label, category, builtin, active, client_rev, created_at, updated_at, deleted_at FROM symptom_definitions
WHERE account_id = ? AND deleted_at IS NULL
ORDER BY builtin DESC, key
`

func (q *Queries) ListSymptomDefinitions(ctx context.Context, accountID string) ([]SymptomDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listSymptomDefinitions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymptomDefinition{}
	for rows.Next() {
		var i SymptomDefinition
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Key,
			&i.Label,
			&i.Category,
			&i.Builtin,
			&i.Active,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymptomLogsByRange = `-- name: ListSymptomLogsByRange :many
SELECT id, account_id, log_date, logged_at, symptom_key, severity, notes, client_rev, created_at, updated_at, deleted_at FROM symptom_logs
WHERE account_id = ? AND deleted_at IS NULL
  AND log_date >= ? AND log_date <= ?
ORDER BY log_date, logged_at
`

type ListSymptomLogsByRangeParams struct {
	AccountID string `json:"account_id"`
	LogDate   string `json:"log_date"`
	LogDate_2 string `json:"log_date_2"`
}

func (q *Queries) ListSymptomLogsByRange(ctx context.Context, arg ListSymptomLogsByRangeParams) ([]SymptomLog, error) {
	rows, err := q.db.QueryContext(ctx, listSymptomLogsByRange, arg.AccountID, arg.LogDate, arg.LogDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymptomLog{}
	for rows.Next() {
		var i SymptomLog
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LogDate,
			&i.LoggedAt,
			&i.SymptomKey,
			&i.Severity,
			&i.Notes,
			&i.ClientRev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBiomarkerObservation = `-- name: UpsertBiomarkerObservation :execrows

INSERT INTO biomarker_observations (
    id, account_id, observed_date, bbt_celsius, bbt_time, bbt_quality,
    cervical_fluid, cervix_position, cervix_firmness,
    notes, client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    observed_date   = excluded.observed_date,
    bbt_celsius     = excluded.bbt_celsius,
    bbt_time        = excluded.bbt_time,
    bbt_quality     = excluded.bbt_quality,
    cervical_fluid  = excluded.cervical_fluid,
    cervix_position = excluded.cervix_position,
    cervix_firmness = excluded.cervix_firmness,
    notes           = excluded.notes,
    client_rev      = excluded.client_rev,
    created_at      = excluded.created_at,
    updated_at      = excluded.updated_at,
    deleted_at      = excluded.deleted_at
WHERE excluded.updated_at > biomarker_observations.updated_at
   OR (excluded.updated_at = biomarker_observations.updated_at
       AND excluded.client_rev > biomarker_observations.client_rev)
`

type UpsertBiomarkerObservationParams struct {
	ID             string          `json:"id"`
	AccountID      string          `json:"account_id"`
	ObservedDate   string          `json:"observed_date"`
	BbtCelsius     sql.NullFloat64 `json:"bbt_celsius"`
	BbtTime        sql.NullString  `json:"bbt_time"`
	BbtQuality     string          `json:"bbt_quality"`
	CervicalFluid  sql.NullString  `json:"cervical_fluid"`
	CervixPosition sql.NullString  `json:"cervix_position"`
	CervixFirmness sql.NullString  `json:"cervix_firmness"`
	Notes          string          `json:"notes"`
	ClientRev      string          `json:"client_rev"`
	CreatedAt      string          `json:"created_at"`
	UpdatedAt      string          `json:"updated_at"`
	DeletedAt      sql.NullString  `json:"deleted_at"`
}

// Biomarker observations ----------------------------------------------------
func (q *Queries) UpsertBiomarkerObservation(ctx context.Context, arg UpsertBiomarkerObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertBiomarkerObservation,
		arg.ID,
		arg.AccountID,
		arg.ObservedDate,
		arg.BbtCelsius,
		arg.BbtTime,
		arg.BbtQuality,
		arg.CervicalFluid,
		arg.CervixPosition,
		arg.CervixFirmness,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertBleedingObservation = `-- name: UpsertBleedingObservation :execrows

INSERT INTO bleeding_observations (
    id, account_id, observed_date, flow, intermenstrual, product_count,
    notes, client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    observed_date  = excluded.observed_date,
    flow           = excluded.flow,
    intermenstrual = excluded.intermenstrual,
    product_count  = excluded.product_count,
    notes          = excluded.notes,
    client_rev     = excluded.client_rev,
    created_at     = excluded.created_at,
    updated_at     = excluded.updated_at,
    deleted_at     = excluded.deleted_at
WHERE excluded.updated_at > bleeding_observations.updated_at
   OR (excluded.updated_at = bleeding_observations.updated_at
       AND excluded.client_rev > bleeding_observations.client_rev)
`

type UpsertBleedingObservationParams struct {
	ID             string         `json:"id"`
	AccountID      string         `json:"account_id"`
	ObservedDate   string         `json:"observed_date"`
	Flow           string         `json:"flow"`
	Intermenstrual int64          `json:"intermenstrual"`
	ProductCount   sql.NullInt64  `json:"product_count"`
	Notes          string         `json:"notes"`
	ClientRev      string         `json:"client_rev"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	DeletedAt      sql.NullString `json:"deleted_at"`
}

// Bleeding observations -----------------------------------------------
func (q *Queries) UpsertBleedingObservation(ctx context.Context, arg UpsertBleedingObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertBleedingObservation,
		arg.ID,
		arg.AccountID,
		arg.ObservedDate,
		arg.Flow,
		arg.Intermenstrual,
		arg.ProductCount,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDailyEntry = `-- name: UpsertDailyEntry :execrows

INSERT INTO daily_entries (
    id, account_id, entry_date, pain_level, mood_level, energy_level,
    notes, client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    entry_date   = excluded.entry_date,
    pain_level   = excluded.pain_level,
    mood_level   = excluded.mood_level,
    energy_level = excluded.energy_level,
    notes        = excluded.notes,
    client_rev   = excluded.client_rev,
    created_at   = excluded.created_at,
    updated_at   = excluded.updated_at,
    deleted_at   = excluded.deleted_at
WHERE excluded.updated_at > daily_entries.updated_at
   OR (excluded.updated_at = daily_entries.updated_at
       AND excluded.client_rev > daily_entries.client_rev)
`

type UpsertDailyEntryParams struct {
	ID          string         `json:"id"`
	AccountID   string         `json:"account_id"`
	EntryDate   string         `json:"entry_date"`
	PainLevel   sql.NullInt64  `json:"pain_level"`
	MoodLevel   sql.NullInt64  `json:"mood_level"`
	EnergyLevel sql.NullInt64  `json:"energy_level"`
	Notes       string         `json:"notes"`
	ClientRev   string         `json:"client_rev"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

// Daily entries --------------------------------------------------------
func (q *Queries) UpsertDailyEntry(ctx context.Context, arg UpsertDailyEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertDailyEntry,
		arg.ID,
		arg.AccountID,
		arg.EntryDate,
		arg.PainLevel,
		arg.MoodLevel,
		arg.EnergyLevel,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMedicationLog = `-- name: UpsertMedicationLog :execrows

INSERT INTO medication_logs (
    id, account_id, log_date, taken_at, name, dose, kind,
    notes, client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    log_date   = excluded.log_date,
    taken_at   = excluded.taken_at,
    name       = excluded.name,
    dose       = excluded.dose,
    kind       = excluded.kind,
    notes      = excluded.notes,
    client_rev = excluded.client_rev,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at
WHERE excluded.updated_at > medication_logs.updated_at
   OR (excluded.updated_at = medication_logs.updated_at
       AND excluded.client_rev > medication_logs.client_rev)
`

type UpsertMedicationLogParams struct {
	ID        string         `json:"id"`
	AccountID string         `json:"account_id"`
	LogDate   string         `json:"log_date"`
	TakenAt   sql.NullString `json:"taken_at"`
	Name      string         `json:"name"`
	Dose      string         `json:"dose"`
	Kind      string         `json:"kind"`
	Notes     string         `json:"notes"`
	ClientRev string         `json:"client_rev"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
}

// Medication logs ---------------------------------------------------------
func (q *Queries) UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertMedicationLog,
		arg.ID,
		arg.AccountID,
		arg.LogDate,
		arg.TakenAt,
		arg.Name,
		arg.Dose,
		arg.Kind,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSymptomDefinition = `-- name: UpsertSymptomDefinition :execrows

INSERT INTO symptom_definitions (
    id, account_id, key, label, category, builtin, active,
    client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    key        = excluded.key,
    label      = excluded.label,
    category   = excluded.category,
    builtin    = excluded.builtin,
    active     = excluded.active,
    client_rev = excluded.client_rev,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    deleted_at = excluded.deleted_at
WHERE excluded.updated_at > symptom_definitions.updated_at
   OR (excluded.updated_at = symptom_definitions.updated_at
       AND excluded.client_rev > symptom_definitions.client_rev)
`

type UpsertSymptomDefinitionParams struct {
	ID        string         `json:"id"`
	AccountID string         `json:"account_id"`
	Key       string         `json:"key"`
	Label     string         `json:"label"`
	Category  string         `json:"category"`
	Builtin   int64          `json:"builtin"`
	Active    int64          `json:"active"`
	ClientRev string         `json:"client_rev"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
}

// Symptom definitions ----------------------------------------------------
func (q *Queries) UpsertSymptomDefinition(ctx context.Context, arg UpsertSymptomDefinitionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSymptomDefinition,
		arg.ID,
		arg.AccountID,
		arg.Key,
		arg.Label,
		arg.Category,
		arg.Builtin,
		arg.Active,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSymptomLog = `-- name: UpsertSymptomLog :execrows

INSERT INTO symptom_logs (
    id, account_id, log_date, logged_at, symptom_key, severity,
    notes, client_rev, created_at, updated_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    log_date    = excluded.log_date,
    logged_at   = excluded.logged_at,
    symptom_key = excluded.symptom_key,
    severity    = excluded.severity,
    notes       = excluded.notes,
    client_rev  = excluded.client_rev,
    created_at  = excluded.created_at,
    updated_at  = excluded.updated_at,
    deleted_at  = excluded.deleted_at
WHERE excluded.updated_at > symptom_logs.updated_at
   OR (excluded.updated_at = symptom_logs.updated_at
       AND excluded.client_rev > symptom_logs.client_rev)
`

type UpsertSymptomLogParams struct {
	ID         string         `json:"id"`
	AccountID  string         `json:"account_id"`
	LogDate    string         `json:"log_date"`
	LoggedAt   string         `json:"logged_at"`
	SymptomKey string         `json:"symptom_key"`
	Severity   int64          `json:"severity"`
	Notes      string         `json:"notes"`
	ClientRev  string         `json:"client_rev"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	DeletedAt  sql.NullString `json:"deleted_at"`
}

// Symptom logs ------------------------------------------------------------
func (q *Queries) UpsertSymptomLog(ctx context.Context, arg UpsertSymptomLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertSymptomLog,
		arg.ID,
		arg.AccountID,
		arg.LogDate,
		arg.LoggedAt,
		arg.SymptomKey,
		arg.Severity,
		arg.Notes,
		arg.ClientRev,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
