// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package dbgen

import (
	"context"
)

const getRecord = `-- name: GetRecord :one
SELECT account_id, entity_id, entity_type, client_rev, ciphertext, deleted, updated_at, recorded_at FROM records WHERE account_id = ? AND entity_id = ?
`

type GetRecordParams struct {
	AccountID string `json:"account_id"`
	EntityID  string `json:"entity_id"`
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, arg.AccountID, arg.EntityID)
	var i Record
	err := row.Scan(
		&i.AccountID,
		&i.EntityID,
		&i.EntityType,
		&i.ClientRev,
		&i.Ciphertext,
		&i.Deleted,
		&i.UpdatedAt,
		&i.RecordedAt,
	)
	return i, err
}

const listRecordsForAccount = `-- name: ListRecordsForAccount :many
SELECT account_id, entity_id, entity_type, client_rev, ciphertext, deleted, updated_at, recorded_at FROM records
WHERE account_id = ?
ORDER BY entity_type, entity_id
`

func (q *Queries) ListRecordsForAccount(ctx context.Context, accountID string) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.AccountID,
			&i.EntityID,
			&i.EntityType,
			&i.ClientRev,
			&i.Ciphertext,
			&i.Deleted,
			&i.UpdatedAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecord = `-- name: UpsertRecord :execrows

INSERT INTO records (
    account_id, entity_id, entity_type, client_rev, ciphertext,
    deleted, updated_at, recorded_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(account_id, entity_id) DO UPDATE SET
    entity_type = excluded.entity_type,
    client_rev  = excluded.client_rev,
    ciphertext  = excluded.ciphertext,
    deleted     = excluded.deleted,
    updated_at  = excluded.updated_at,
    recorded_at = excluded.recorded_at
WHERE excluded.updated_at > records.updated_at
   OR (excluded.updated_at = records.updated_at AND excluded.client_rev > records.client_rev)
`

type UpsertRecordParams struct {
	AccountID  string `json:"account_id"`
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	ClientRev  string `json:"client_rev"`
	Ciphertext []byte `json:"ciphertext"`
	Deleted    int64  `json:"deleted"`
	UpdatedAt  string `json:"updated_at"`
	RecordedAt string `json:"recorded_at"`
}

// Sealed record storage. Content is opaque to this server; only the routing
// metadata below is readable.
//
// Entity-level last-write-wins: the update applies only when the incoming
// record is newer (updated_at, then client_rev). Affected rows = 0 means the
// pushed record lost; the handler returns the server state as a conflict.
func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertRecord,
		arg.AccountID,
		arg.EntityID,
		arg.EntityType,
		arg.ClientRev,
		arg.Ciphertext,
		arg.Deleted,
		arg.UpdatedAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
