// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT account_id, settings_ciphertext, updated_at FROM account_settings WHERE account_id = ?
`

func (q *Queries) GetSettings(ctx context.Context, accountID string) (AccountSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings, accountID)
	var i AccountSetting
	err := row.Scan(&i.AccountID, &i.SettingsCiphertext, &i.UpdatedAt)
	return i, err
}

const insertDefaultSettings = `-- name: InsertDefaultSettings :exec

INSERT INTO account_settings (account_id, updated_at)
VALUES (?, ?)
`

type InsertDefaultSettingsParams struct {
	AccountID string `json:"account_id"`
	UpdatedAt string `json:"updated_at"`
}

// Settings content (life stage, tracking focuses) is Art. 9 health data and is
// sealed client-side like every other record.
func (q *Queries) InsertDefaultSettings(ctx context.Context, arg InsertDefaultSettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultSettings, arg.AccountID, arg.UpdatedAt)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE account_settings
SET settings_ciphertext = ?, updated_at = ?
WHERE account_id = ?
`

type UpdateSettingsParams struct {
	SettingsCiphertext []byte `json:"settings_ciphertext"`
	UpdatedAt          string `json:"updated_at"`
	AccountID          string `json:"account_id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings, arg.SettingsCiphertext, arg.UpdatedAt, arg.AccountID)
	return err
}
