// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT account_id, locale, time_zone, life_stage, tracking_focus, updated_at FROM account_settings WHERE account_id = ?
`

func (q *Queries) GetSettings(ctx context.Context, accountID string) (AccountSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings, accountID)
	var i AccountSetting
	err := row.Scan(
		&i.AccountID,
		&i.Locale,
		&i.TimeZone,
		&i.LifeStage,
		&i.TrackingFocus,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDefaultSettings = `-- name: InsertDefaultSettings :exec
INSERT INTO account_settings (account_id, updated_at)
VALUES (?, ?)
`

type InsertDefaultSettingsParams struct {
	AccountID string `json:"account_id"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertDefaultSettings(ctx context.Context, arg InsertDefaultSettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultSettings, arg.AccountID, arg.UpdatedAt)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE account_settings
SET locale = ?, time_zone = ?, life_stage = ?, tracking_focus = ?, updated_at = ?
WHERE account_id = ?
`

type UpdateSettingsParams struct {
	Locale        string `json:"locale"`
	TimeZone      string `json:"time_zone"`
	LifeStage     string `json:"life_stage"`
	TrackingFocus string `json:"tracking_focus"`
	UpdatedAt     string `json:"updated_at"`
	AccountID     string `json:"account_id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings,
		arg.Locale,
		arg.TimeZone,
		arg.LifeStage,
		arg.TrackingFocus,
		arg.UpdatedAt,
		arg.AccountID,
	)
	return err
}
