// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"
	"database/sql"
)

const latestCursor = `-- name: LatestCursor :one
SELECT seq FROM sync_changes WHERE account_id = ? ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LatestCursor(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestCursor, accountID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const pullChanges = `-- name: PullChanges :many
SELECT seq, entity_type, entity_id, deleted, payload, updated_at, recorded_at
FROM sync_changes
WHERE account_id = ? AND seq > ?
ORDER BY seq
LIMIT ?
`

type PullChangesParams struct {
	AccountID string `json:"account_id"`
	Seq       int64  `json:"seq"`
	Limit     int64  `json:"limit"`
}

type PullChangesRow struct {
	Seq        int64          `json:"seq"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	Deleted    int64          `json:"deleted"`
	Payload    sql.NullString `json:"payload"`
	UpdatedAt  string         `json:"updated_at"`
	RecordedAt string         `json:"recorded_at"`
}

func (q *Queries) PullChanges(ctx context.Context, arg PullChangesParams) ([]PullChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, pullChanges, arg.AccountID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullChangesRow{}
	for rows.Next() {
		var i PullChangesRow
		if err := rows.Scan(
			&i.Seq,
			&i.EntityType,
			&i.EntityID,
			&i.Deleted,
			&i.Payload,
			&i.UpdatedAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChange = `-- name: RecordChange :one
INSERT INTO sync_changes (
    account_id, entity_type, entity_id, deleted, payload, updated_at, recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING seq
`

type RecordChangeParams struct {
	AccountID  string         `json:"account_id"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	Deleted    int64          `json:"deleted"`
	Payload    sql.NullString `json:"payload"`
	UpdatedAt  string         `json:"updated_at"`
	RecordedAt string         `json:"recorded_at"`
}

func (q *Queries) RecordChange(ctx context.Context, arg RecordChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordChange,
		arg.AccountID,
		arg.EntityType,
		arg.EntityID,
		arg.Deleted,
		arg.Payload,
		arg.UpdatedAt,
		arg.RecordedAt,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
